name: Grade Solution

on: push


jobs:
  send-grade-to-grader:
    name: Grade Solution
    runs-on: ubuntu-latest

    steps:
      - name: Send Repository Dispatch to private repo
        run: |
          curl \
          -X POST \
          -u "${{ secrets.PAT_USERNAME }}:${{ secrets.PAT_TOKEN }}" \
          -H "Accept: application/vnd.github.everest-preview+json" \
          https://api.github.com/repos/${{ secrets.PAT_USERNAME }}/${{ secrets.GRADING_REPO }}/dispatches \
          --data '{"event_type": "pull-trigger", "client_payload": {"project": "spotifly", "repo": "@github.com/ThatcherT/spotifly.git"}}'